# Generated by Django 3.2.25 on 2025-06-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JugadorRugby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('equipo', models.CharField(max_length=100)),
                ('partidos_jugados', models.IntegerField()),
                ('tries', models.IntegerField()),
                ('puntos', models.IntegerField()),
            ],
        ),
    ]
