# Generated by Django 3.2.25 on 2025-06-24 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rugby', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugadorrugby',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
