# Generated by Django 3.2.25 on 2025-06-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rugby', '0002_jugadorrugby_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugadorrugby',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='jugadores/'),
        ),
    ]
